import '~/styles/globals.css';

import { Inter as FontSans } from 'next/font/google';
import { getServerAuthSession } from '~/server/auth';
import { redirect } from 'next/navigation';
import Link from 'next/link';
import NavBarAvatar from './_components/NavBarAvatar';

export const metadata = {
	title: 'Shadowdark Torch Manager',
	description: 'Generated by create-t3-app',
	icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const fontSans = FontSans({
	subsets: ['latin'],
	variable: '--font-sans',
});

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const session = await getServerAuthSession();

	if (!session) {
		redirect('/api/auth/signin');
	}

	return (
		<html lang="en" className={`${fontSans.variable}`}>
			<body className="flex min-h-screen flex-col bg-slate-800 text-white">
				<header>
					<nav className="m-0 h-14 w-full bg-slate-500 p-0">
						<div className="flex h-full w-full flex-grow items-center justify-start space-x-4 px-4">
							<Link href="/">Home</Link>
							<Link href="/about">About</Link>
							<div className="flex flex-grow justify-end">
								<NavBarAvatar
									username={session?.user?.name ?? 'Torch'}
								/>
							</div>
						</div>
					</nav>
				</header>
				{children}
			</body>
		</html>
	);
}
